using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Text;
using System.Data;

public partial class Design_IPD_DeathCertificateEntryReport : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            txtFromDate.Text = txtTodate.Text = DateTime.Now.ToString("dd-MMM-yyyy");
        }
        txtFromDate.Attributes.Add("ReadOnly", "true");
        txtTodate.Attributes.Add("ReadOnly", "true");
    }
    protected void btnReport_Click(object sender, EventArgs e)
    {
        StringBuilder sb = new StringBuilder();
       sb.Append(" SELECT  dc.`CertificateNo`,dc.`PatientID` 'UHID',REPLACE(dc.`TransactionID`,'ISHHI','') 'IPD No',dc.`Name`, ");
       sb.Append(" dc.`RelationName`,dc.`Gender`,dc.`Age`,dc.`Address`,DATE_FORMAT(dc.`EntryDate`,'%d-%b-%Y') 'Entry Date', ");
       sb.Append(" DATE_FORMAT(dc.`PronounceDate`,'%d-%b-%Y')PronounceDate,TIME_FORMAT(dc.`PronounceTime`,'%h:%i %p')PronounceTime, ");
       sb.Append(" DATE_FORMAT(dc.`DeathDate`,'%d-%b-%Y')DeathDate,TIME_FORMAT(dc.`DeathTime`,'%h:%i %p')DeathTime,dc.`DeathNature`,dc.`DeathCause`, ");
       sb.Append(" dc.`DoctorName` 'Under Doctor',dc.`CertifiedDoctorName` 'Death Certified Doctor',dc.`BodyHandOveredTo`, ");
       sb.Append(" (SELECT CONCAT(em.Title,' ',em.Name) FROM employee_master  em WHERE em.Employee_ID=dc.USERID)'Generated By', ");
       sb.Append(" IFNULL((SELECT CONCAT(em.Title,' ',em.Name) FROM employee_master  em WHERE em.Employee_ID= dc.`UpdatedBy`),'')'Last Update By', ");
       sb.Append(" IFNULL(DATE_FORMAT(dc.`UpdatedDate`,'%d-%b-%Y'),'')'Last Updated Date' FROM deathcertificate dc ");
       sb.Append(" WHERE dc.`EntryDate`>='"+Util.GetDateTime(txtFromDate.Text).ToString("yyyy-MM-dd")+" 00:00:00' ");
       sb.Append(" AND dc.`EntryDate`<='" + Util.GetDateTime(txtTodate.Text).ToString("yyyy-MM-dd") + " 23:59:59' ");
       DataTable dt = StockReports.GetDataTable(sb.ToString());
       if (dt.Rows.Count > 0)
       {
           Session["dtExport2Excel"] = dt;
           Session["ReportName"] = "Death Certificate Entry Report";
           Session["Period"] = "As On Date " + txtFromDate.Text + " And Time " + txtTodate.Text.Trim();
           ScriptManager.RegisterStartupScript(this, this.GetType(), "Key1", "window.open('../../Design/common/ExportToExcel.aspx');", true);
           lblMsg.Text = dt.Rows.Count + " Records Found";
       }
       else
       {
           lblMsg.Text = "No Record Found";
       }

    }
}